name: compass
description: "A compass plugin for flutter."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: studio.midoridesign.compass
        pluginClass: CompassPlugin
      ios:
        pluginClass: CompassPlugin
